import { AdminShell } from "@/components/app-shell";
import { EmptyState } from "@/components/ui";
import { requireAdmin } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { AdminQueue } from "@/components/admin-queue";

export default async function AdminPage() {
	await requireAdmin();
	const admin = createAdminClient();
	const [users, hosts, reports, payments, violations] = await Promise.all([
		admin.from("profiles").select("id", { count: "exact", head: true }).eq("role", "user"),
		admin.from("profiles").select("id", { count: "exact", head: true }).eq("role", "host"),
		admin.from("reports").select("id", { count: "exact", head: true }).eq("status", "open"),
		admin.from("payment_verifications").select("id", { count: "exact", head: true }).eq("status", "awaiting_review"),
		admin.from("violations").select("id", { count: "exact", head: true }).eq("status", "flagged"),
	]);
	const modules = ["Overview", "Users", "Hosts", "Profiles", "Admin-Created Profiles", "Discover Management", "Matches", "Conversations", "Video Calls", "Reports", "Moderation", "Violations", "Wallet", "Payments", "Coin Packages", "Host Earnings", "Withdrawals", "Blocks", "Notifications", "Audit Logs", "System Settings"];
	return <AdminShell><span className="eyebrow">Private operations</span><h1 className="serif">Admin overview</h1><p className="muted">Sensitive moderation and payment decisions are server-authorized and audit logged.</p><div className="stats-grid"><div className="stat"><span className="eyebrow">Users</span><strong>{users.count || 0}</strong></div><div className="stat"><span className="eyebrow">Hosts</span><strong>{hosts.count || 0}</strong></div><div className="stat"><span className="eyebrow">Open reports</span><strong>{reports.count || 0}</strong></div><div className="stat"><span className="eyebrow">Payment review</span><strong>{payments.count || 0}</strong></div><div className="stat"><span className="eyebrow">Moderation flags</span><strong>{violations.count || 0}</strong></div></div><section style={{ marginTop: "2rem" }}><h2>Operations modules</h2><div className="choice-grid">{modules.map((module) => <div className="choice-card" key={module}><span className="eyebrow">Admin</span><h3>{module}</h3><p className="muted">Protected operational module.</p></div>)}</div></section><section style={{ marginTop: "2rem" }}><EmptyState title="Review queues stay server-controlled" message="Use the protected API decisions for payments and violations. No internal moderation metadata is exposed to Users or Hosts." /></section></AdminShell>;
	return <AdminShell><span className="eyebrow">Private operations</span><h1 className="serif">Admin overview</h1><p className="muted">Sensitive moderation and payment decisions are server-authorized and audit logged.</p><div className="stats-grid"><div className="stat"><span className="eyebrow">Users</span><strong>{users.count || 0}</strong></div><div className="stat"><span className="eyebrow">Hosts</span><strong>{hosts.count || 0}</strong></div><div className="stat"><span className="eyebrow">Open reports</span><strong>{reports.count || 0}</strong></div><div className="stat"><span className="eyebrow">Payment review</span><strong>{payments.count || 0}</strong></div><div className="stat"><span className="eyebrow">Moderation flags</span><strong>{violations.count || 0}</strong></div></div><section style={{ marginTop: "2rem" }}><h2>Review queue</h2><AdminQueue /></section><section style={{ marginTop: "2rem" }}><h2>Operations modules</h2><div className="choice-grid">{modules.map((module) => <div className="choice-card" key={module}><span className="eyebrow">Admin</span><h3>{module}</h3><p className="muted">Protected operational module.</p></div>)}</div></section><section style={{ marginTop: "2rem" }}><EmptyState title="Review actions stay server-controlled" message="Use the protected API decisions for payments, violations, and Host verification. No internal moderation metadata is exposed to Users or Hosts." /></section></AdminShell>;
}