"use client";

import { useEffect, useState } from "react";
import { Button, Loading } from "@/components/ui";

type Kind = "payments" | "google-play" | "reports" | "violations" | "host-verification" | "users" | "hosts";
type Item = Record<string, unknown>;
export function AdminQueue() {
  const [kind, setKind] = useState<Kind>("payments"); const [items, setItems] = useState<Item[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [search, setSearch] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active=true; async function load() { setLoading(true); const response=await fetch(`/api/admin/queue?kind=${kind}&page=${page}&search=${encodeURIComponent(search)}`); const result=await response.json() as { items?: Item[]; total?: number; error?: string }; if (!active) return; if (!response.ok) setError(result.error || "Queue could not be loaded."); else { setItems(result.items || []); setTotal(result.total || 0); setError(""); } setLoading(false); } void load(); return () => { active=false; }; }, [kind, page, search]);
  async function decide(item: Item, decision: string, endpoint: string) { if (!window.confirm(`Confirm ${decision}?`)) return; const response = await fetch(`${endpoint}/${String(item.id)}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }); const result = await response.json() as { error?: string }; if (!response.ok) setError(result.error || "Action could not be completed."); else setItems((current) => current.filter((entry) => entry.id !== item.id)); }
  function actions(item: Item) { if (kind === "payments") return <><Button type="button" onClick={() => void decide(item, "approve", "/api/admin/payments")}>Approve</Button><Button type="button" variant="danger" onClick={() => void decide(item, "reject", "/api/admin/payments")}>Reject</Button></>; if (kind === "violations") return <><Button type="button" onClick={() => void decide(item, "confirm", "/api/admin/violations")}>Confirm</Button><Button type="button" variant="quiet" onClick={() => void decide(item, "dismiss", "/api/admin/violations")}>Dismiss</Button></>; if (kind === "host-verification") return <><Button type="button" onClick={() => void decide(item, "approve", "/api/admin/host-verification")}>Approve</Button><Button type="button" variant="danger" onClick={() => void decide(item, "reject", "/api/admin/host-verification")}>Reject</Button></>; return null; }
  return <section className="choice-card"><div className="form-footer"><label htmlFor="admin-queue">Queue</label><select id="admin-queue" value={kind} onChange={(event) => { setKind(event.target.value as Kind); setPage(1); }}><option value="payments">UPI Payments</option><option value="google-play">Google Play Purchases</option><option value="reports">Reports</option><option value="violations">Violations</option><option value="host-verification">Host verification</option><option value="users">Users</option><option value="hosts">Hosts</option></select>{(kind === "users" || kind === "hosts") && <input aria-label="Search queue" placeholder="Search email or name" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} />}</div>{loading ? <Loading label="Loading admin queue" /> : error ? <p role="alert" className="muted">{error}</p> : items.length ? <div>{items.map((item, index) => <article className="choice-card" key={String(item.id || index)}><pre>{JSON.stringify(item, null, 2)}</pre><div className="form-footer">{actions(item)}</div></article>)}</div> : <p className="muted">No records in this queue.</p>}<div className="form-footer"><Button type="button" variant="quiet" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}>Previous</Button><span className="muted">Page {page} · {total} records</span><Button type="button" variant="quiet" disabled={page * 25 >= total} onClick={() => setPage((current) => current + 1)}>Next</Button></div></section>;
}
