"use client";
import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { Button, Input } from "@/components/ui";
import { Capacitor } from "@capacitor/core";
import { GOOGLE_PLAY_PRODUCTS } from "@/components/google-play-wallet";

type Package={id:string;coins:number;price_rupees?:number};
type Order={id:string;coins:number;expected_amount_paise:number;upi_uri:string;status:string;expires_at:string};
type Props={hostId?:string;hostName?:string;open?:boolean;initialPackageId?:string;onClose?:()=>void;onVerified?:(coins:number)=>void};
const FALLBACK_PACKAGES:Package[]=GOOGLE_PLAY_PRODUCTS.map(p=>({id:p.id,coins:p.coins,price_rupees:p.coins}));

export function CoinPurchaseFlow({hostId,hostName,open=true,initialPackageId,onClose,onVerified}:Props){
 const [packages,setPackages]=useState<Package[]>([]),[selected,setSelected]=useState<Package|null>(null),[order,setOrder]=useState<Order|null>(null),[utr,setUtr]=useState(""),[transactionId,setTransactionId]=useState(""),[screenshot,setScreenshot]=useState<File|null>(null),[step,setStep]=useState("choose"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[verifiedCoins,setVerifiedCoins]=useState(0),[copied,setCopied]=useState(false);
 const android=Capacitor.isNativePlatform()&&Capacitor.getPlatform()==="android";
 useEffect(()=>{if(!open)return;fetch("/api/wallet",{cache:"no-store"}).then(r=>r.json()).then(x=>{if(x.packages){setPackages(x.packages);if(initialPackageId){const p=x.packages.find((v:Package)=>v.id===initialPackageId);if(p){setSelected(p);setStep("confirm")}}}else setMessage(x.error||"Packages unavailable.")}).catch(()=>setMessage("Packages unavailable."))},[open,initialPackageId]);
 useEffect(()=>{const h=(e:Event)=>{const d=(e as CustomEvent).detail||{};if(hostId&&d.hostId&&d.hostId!==hostId)return;if(Number(d.coins)>0){setVerifiedCoins(Number(d.coins));setStep("success");}};window.addEventListener("ishqiya-purchase-complete",h);return()=>window.removeEventListener("ishqiya-purchase-complete",h)},[hostId]);
 useEffect(()=>{if(step!=="pending"||!order)return;let stop=false;let timer:ReturnType<typeof setTimeout>;const check=async()=>{try{const r=await fetch(`/api/wallet/order-status?orderId=${encodeURIComponent(order.id)}`,{cache:"no-store"});const x=await r.json();if(stop)return;if(r.ok&&x.status==="approved"){setVerifiedCoins(Number(x.coins||order.coins));setStep("success");window.dispatchEvent(new CustomEvent("ishqiya-wallet-refresh"));return}if(r.ok&&(x.status==="rejected"||x.status==="expired")){setMessage(x.status==="expired"?"This payment order expired. Please try again.":"Payment could not be verified. Please try again.");setStep("choose");return}}catch{}if(!stop)timer=setTimeout(check,5000)};void check();return()=>{stop=true;clearTimeout(timer)}},[step,order]);
 if(!open)return null;
 const close=()=>{if(!busy)onClose?.()};
 const pay=async()=>{if(!selected||busy)return;setBusy(true);setMessage("");try{if(android){window.dispatchEvent(new CustomEvent("ishqiya-buy-coins",{detail:{productId:`coins_${selected.coins}`,hostId,hostName}}));setMessage("Opening Google Play…");return}const r=await fetch("/api/wallet",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageId:selected.id,coins:selected.coins})});const x=await r.json();if(!r.ok||!x.order)throw new Error(x.error||"Payment order could not be created.");setOrder(x.order);setStep("pay");}catch(e){setMessage(e instanceof Error?e.message:"Payment could not be started")}finally{setBusy(false)}};
 const openUpi=()=>{if(!order)return;window.location.href=order.upi_uri;};
 const copyUpi=async()=>{if(!order)return;try{const params=new URL(order.upi_uri).searchParams;const pa=params.get("pa")||"";await navigator.clipboard.writeText(pa);setCopied(true);setTimeout(()=>setCopied(false),1800)}catch{setMessage("Could not copy the UPI ID. Please use the payment button.")}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!order||!screenshot||busy)return;setBusy(true);setMessage("");try{const f=new FormData();f.set("orderId",order.id);f.set("utr",utr.trim());f.set("transactionId",transactionId.trim());f.set("screenshot",screenshot);const r=await fetch("/api/wallet/proof",{method:"POST",body:f});const x=await r.json();if(!r.ok)throw new Error(x.error||"Proof could not be submitted.");setStep("pending");setMessage("Payment submitted. Coins will be added after verification.")}catch(e){setMessage(e instanceof Error?e.message:"Proof could not be submitted")}finally{setBusy(false)}};
 return <div role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.72)",display:"grid",placeItems:"center",padding:"1rem"}}><section className="form-card" style={{width:"100%",maxWidth:520,maxHeight:"90vh",overflowY:"auto",borderRadius:28}}><div style={{display:"flex",justifyContent:"space-between",gap:"1rem"}}><div><span className="eyebrow">{hostName?`Call with ${hostName}`:"Coins"}</span><h2 className="serif">{step==="success"?"Payment successful":step==="pay"?"Pay securely with UPI":"Choose coins to continue"}</h2></div><button type="button" onClick={close} aria-label="Close" style={{border:0,background:"transparent",fontSize:"1.5rem",cursor:"pointer"}}>×</button></div>
 {step==="choose"&&<><p className="muted">Choose a package. The amount is fixed by Ishqiya.</p><div style={{display:"grid",gap:".65rem"}}>{(packages.length?packages:FALLBACK_PACKAGES).map(p=><button key={p.id} type="button" className="choice-card" onClick={()=>{setSelected(p);setStep("confirm")}} style={{display:"flex",justifyContent:"space-between",textAlign:"left"}}><span><strong>{p.coins.toLocaleString("en-IN")} coins</strong><span className="muted" style={{display:"block"}}>₹{Number(p.price_rupees??p.coins).toLocaleString("en-IN")}</span></span><span>Select →</span></button>)}</div></>}
 {step==="confirm"&&selected&&<><div className="choice-card"><span className="eyebrow">Amount locked</span><strong style={{display:"block",fontSize:"1.5rem"}}>{selected.coins.toLocaleString("en-IN")} Coins — ₹{Number(selected.price_rupees??selected.coins).toLocaleString("en-IN")}</strong><p className="muted">This amount is fixed by the selected package and cannot be changed.</p></div><Button type="button" disabled={busy} onClick={()=>void pay()} style={{width:"100%"}}>{android?"Continue to Google Play":`Continue to UPI`}</Button></>}
 {step==="pay"&&order&&<div style={{display:"grid",gap:".8rem"}}><div className="choice-card" style={{textAlign:"center"}}><span className="eyebrow">Amount locked</span><strong style={{display:"block",fontSize:"1.7rem"}}>₹{(order.expected_amount_paise/100).toLocaleString("en-IN")}</strong><p className="muted">Choose any UPI app on your phone. The amount is fixed.</p></div><Button type="button" onClick={openUpi} style={{width:"100%"}}>Open UPI App</Button><button type="button" className="button button-secondary" onClick={copyUpi} style={{width:"100%"}}>{copied?"UPI ID Copied ✓":"Copy UPI ID"}</button><p className="muted" style={{textAlign:"center",margin:0}}>If the UPI app does not open, copy the UPI ID and pay ₹{(order.expected_amount_paise/100).toLocaleString("en-IN")} manually. Then continue below.</p><Button type="button" variant="secondary" onClick={()=>setStep("proof")} style={{width:"100%"}}>I Have Paid → Enter UTR</Button></div>}
 {step==="proof"&&order&&<form onSubmit={submit} style={{display:"grid",gap:".8rem"}}><div className="choice-card"><span className="eyebrow">Payment amount</span><strong>₹{(order.expected_amount_paise/100).toLocaleString("en-IN")}</strong><p className="muted">Pay the exact amount, then enter the real UTR and upload the payment screenshot.</p></div><Button type="button" variant="secondary" onClick={openUpi}>Open UPI App Again</Button><Input id="proof-utr" label="UTR" value={utr} onChange={e=>setUtr(e.target.value)} required/><Input id="proof-tx" label="Transaction ID" value={transactionId} onChange={e=>setTransactionId(e.target.value)} required/><Input id="proof-shot" label="Payment screenshot" type="file" accept="image/*" onChange={e=>setScreenshot(e.target.files?.[0]||null)} required/><Button type="submit" disabled={busy}>{busy?"Submitting…":"Submit for Verification"}</Button></form>}
 {step==="pending"&&<div className="choice-card"><strong>⏳ Verification pending</strong><p className="muted">Keep this screen open. Coins are added only after verification.</p></div>}
 {step==="success"&&<div style={{display:"grid",gap:"1rem"}}><div className="choice-card" style={{textAlign:"center"}}><div style={{fontSize:"2rem"}}>🎉</div><strong>{verifiedCoins.toLocaleString("en-IN")} Coins Added Successfully!</strong><p className="muted">Your verified coins have been credited.</p>{hostName&&<p><strong>You can now call {hostName}.</strong></p>}</div>{hostId?<Button type="button" onClick={()=>onVerified?.(verifiedCoins)} style={{width:"100%"}}>▶ Start Video Call</Button>:<Button type="button" onClick={close} style={{width:"100%"}}>Done</Button>}</div>}
 {message&&<p className="muted" role="status">{message}</p>}</section></div>;
}